package cn.zjut.entity;

// Generated 2013-5-12 13:06:50 by Hibernate Tools 3.2.2.GA

/**
 * Semanticlocation generated by hbm2java
 */
public class Semanticlocation implements java.io.Serializable {

	private int id;
	private Float maxlatitude;
	private Float minlatitude;
	private Float maxlongitude;
	private Float minlongitude;
	private Integer time;
	private Integer weight;
	private String semantic;

	public Semanticlocation() {
	}

	public Semanticlocation(int id) {
		this.id = id;
	}

	public Semanticlocation(int id, Float maxlatitude, Float minlatitude,
			Float maxlongitude, Float minlongitude, Integer time,
			Integer weight, String semantic) {
		this.id = id;
		this.maxlatitude = maxlatitude;
		this.minlatitude = minlatitude;
		this.maxlongitude = maxlongitude;
		this.minlongitude = minlongitude;
		this.time = time;
		this.weight = weight;
		this.semantic = semantic;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Float getMaxlatitude() {
		return this.maxlatitude;
	}

	public void setMaxlatitude(Float maxlatitude) {
		this.maxlatitude = maxlatitude;
	}

	public Float getMinlatitude() {
		return this.minlatitude;
	}

	public void setMinlatitude(Float minlatitude) {
		this.minlatitude = minlatitude;
	}

	public Float getMaxlongitude() {
		return this.maxlongitude;
	}

	public void setMaxlongitude(Float maxlongitude) {
		this.maxlongitude = maxlongitude;
	}

	public Float getMinlongitude() {
		return this.minlongitude;
	}

	public void setMinlongitude(Float minlongitude) {
		this.minlongitude = minlongitude;
	}

	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public String getSemantic() {
		return this.semantic;
	}

	public void setSemantic(String semantic) {
		this.semantic = semantic;
	}

}
